
/*
 * =============================================  TASK LIST | DUE 20/4/2017  ===================================================
 * 
 *     0- GETSTARTED introductory button for explaining the UX in not-so-boring detail! 
 * 
 *     1- create and integrate mongoDB database for entries/user information.
 *     2- create selfie game rules and responses.
 *     3- create multimedia interactions rules and responses.
 * 
 *     4- create emotional responses ONLY on an entire log entry and store the current emotions in DB with entry. 
 *          - get TONE analysis / personality / emotions and sentiment in a formula to produce a response | and store! 
 *          - react to emotion with multimedia too. 
 * 
 *     5- create contextually relevant messengerAPI related features (look at paper).  
 *     6- handling emojis + emoji sentiment? (outside diary context/ inside diary context). 
 *     7- create animated visual response (animating GIF for CHATZER EYE) | In response to what though?
 *     8- translating from any input language to ENGLISH back and forth between messenger/API.AI 
 *     9- putting a GIPHY in proper card showing the BANNER. 
 *    10- PUSH notifications after a long time of inactivity (push with what's your status or check the media out! )
 * 
 * =============================================================================================================================
 */

